# stable identities: raft-0, raft-1, raft-2
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: raft
spec:
  serviceName: raft-headless
  replicas: 3
  selector:
    matchLabels:
      app: raft
  template:
    metadata:
      labels:
        app: raft
    spec:
      containers:
        - name: raft-server
          image: raft-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: server-port
